openapi: 3.0.0
info:
  description: This API is a test
  title: Testing API
  version: 1.0.0
paths:
  /profiles:
    get:
      summary: 'get all profiles'
      operationId: 'get-profiles'
      responses:
        200:
          description: OK
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ValidTakeoverProfiles'

components:
  schemas:
    ValidTakeoverProfiles:
      type: object
      properties:
        profiles:
          type: array
          items:
            type: object
            properties:
              profileName:
                type: string
              tariffType:
                type: string
              mergedConfigId:
                type: string
              value:
                type: number
              tag:
                type: string
              unit:
                type: string
    